version: '{branch}-{build}'
skip_tags: true
clone_folder: c:\gopath\src\perkeep.org
for:
- 
  matrix:
    only:
      - image: Ubuntu
  clone_folder: /go/src/perkeep.org
environment:
  matrix: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GOPATH: c:\gopath
      PATH: c:\gopath\bin;c:\go\bin;%PATH%
      CGO_ENABLED: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      GOPATH: /go
      PATH: /go/bin:/usr/local/go/bin:$PATH
build_script:
- go run make.go
test_script:
- devcam test
