version: '{branch}-{build}'
skip_tags: true
for:
-
  matrix:
    only: 
      - image: Ubuntu
  clone_folder: /usr/go/src
  environment:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      GOPATH: /usr/go/

-
  matrix:
    only:
      - image: Visual Studio 2017
  clone_folder: c:\gopath\src\perkeep.org
  environment:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GOPATH: c:\gopath
      PATH: c:\gopath\bin;c:\go\bin;%PATH%
      CGO_ENABLED: 0

build_script:
- cmd: go run make.go
test_script:
- cmd: devcam test
