sudo: required
dist: trusty
go_import_path: perkeep.org
language: go
go:
  - "1.13.x"
before_install:
  - sudo apt-get install -qq pkg-config fuse build-essential
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
install: go run make.go -v=true -sqlite=true
script: ${GOPATH}/bin/devcam test -sqlite=true
